version: "3.9"

services:
  runner:
    build: .
    image: alchemyfr/github-runner:latest
    environment:
      RUNNER_NAME: "my-runner"
      RUNNER_LABELS: "self-hosted"
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: ${RUNNER_REPLICAS}
